baseURL = "https://sunstars.ml"
languageCode = "zh-hans"
title = "玄学少年易先生"
theme = "maupassant"
## googleAnalytics = ""  # UA-XXXXXXXX-X/G-XXXXXXXXXX

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 200

## disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "易先生"

[params]
  author = "易先生"
  subtitle = "大道至简，自圆其说"
  keywords = "周易,八字,梅花易数,六爻"
  description = "有缘自会相见"
  busuanzi = true #启用不算子网页统计
  ## googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = false  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "玄学少年易先生"
  name = "易先生"
  url = "https://sunstars.ml"


## 侧边栏广告位
[[params.ads]]
  title = "我的个人微信"
  url = "/about/qrcode_for_weixin.jpg"
  img = "/about/qrcode_for_weixin.jpg"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "spacezonealpha/comment" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "易先生原创"
    link = "https://sunstars.ml"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "suibi"
    name = "随笔"
    url = "/categories/随笔"
    weight = 2

  [[menu.main]]
    identifier = "fenxi"
    name = "分析"
    url = "/categories/分析"
    weight = 3

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 4

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5